#!/usr/bin/env python3
"""Build data/strategy_skill.xml from all skills/*/SKILL.md files."""

import os
import sys
import re
import xml.sax.saxutils as saxutils

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
MODULE_DIR = os.path.dirname(os.path.dirname(SCRIPT_DIR))
SKILLS_DIR = os.path.join(MODULE_DIR, 'static', 'skills')
OUTPUT_DIR = os.path.join(MODULE_DIR, 'data')
OUTPUT_FILE = os.path.join(OUTPUT_DIR, 'strategy_skill.xml')


def parse_frontmatter(content):
    """Extract YAML frontmatter and body from SKILL.md content."""
    if not content.startswith('---'):
        return {}, content

    parts = content.split('---', 2)
    if len(parts) < 3:
        return {}, content

    frontmatter = {}
    body = parts[2].strip()

    for line in parts[1].strip().split('\n'):
        line = line.strip()
        if ':' in line:
            key, val = line.split(':', 1)
            frontmatter[key.strip()] = val.strip()

    return frontmatter, body


def main():
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    skills = []
    for skill_name in sorted(os.listdir(SKILLS_DIR)):
        skill_dir = os.path.join(SKILLS_DIR, skill_name)
        skill_file = os.path.join(skill_dir, 'SKILL.md')
        if not os.path.isfile(skill_file):
            continue

        with open(skill_file, 'r') as f:
            content = f.read()

        fm, body = parse_frontmatter(content)
        if not fm.get('name'):
            print(f"WARNING: {skill_file} has no name in frontmatter, skipping")
            continue

        skills.append({
            'name': fm['name'],
            'description': fm.get('description', ''),
            'version': (fm.get('metadata') or {}).get('version', fm.get('version', '1.0.0')),
            'body': body,
            'skill_path': f'static/skills/{skill_name}/SKILL.md',
        })

    # Generate XML
    xml_parts = ['<?xml version="1.0" encoding="utf-8"?>']
    xml_parts.append('<odoo>')
    xml_parts.append('  <!-- Auto-generated by static/scripts/build_skill_xml.py -->')
    xml_parts.append('  <!-- DO NOT EDIT MANUALLY -->')
    xml_parts.append('')

    for i, skill in enumerate(skills):
        xml_id = f"strategy_skill_{skill['name'].replace('-', '_')}"
        xml_parts.append(f'  <record id="{xml_id}" model="strategy.skill">')
        xml_parts.append(f'    <field name="name">{saxutils.escape(skill["name"])}</field>')
        xml_parts.append(f'    <field name="description">{saxutils.escape(skill["description"])}</field>')
        xml_parts.append(f'    <field name="category">strategy</field>')
        xml_parts.append(f'    <field name="version">{saxutils.escape(skill["version"])}</field>')
        xml_parts.append(f'    <field name="is_base" eval="True"/>')
        xml_parts.append(f'    <field name="is_active" eval="True"/>')
        xml_parts.append(f'    <field name="skill_content"><![CDATA[')
        xml_parts.append(skill['body'])
        xml_parts.append(f']]></field>')
        xml_parts.append(f'  </record>')
        xml_parts.append('')

    xml_parts.append('</odoo>')
    xml_parts.append('')

    with open(OUTPUT_FILE, 'w') as f:
        f.write('\n'.join(xml_parts))

    print(f"Generated {OUTPUT_FILE} with {len(skills)} skills")
    for s in skills:
        print(f"  ✓ {s['name']}")


if __name__ == '__main__':
    main()
