# Copyright (C) 2026 Vertel Sverige AB (<https://vertel.se>).
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).

from odoo.tests.common import TransactionCase, tagged


@tagged('post_install', '-at_install')
class TestBusinessModelCanvas(TransactionCase):

    @classmethod
    def setUpClass(cls):
        super().setUpClass()
        cls.BMC = cls.env['business.model.canvas']

    def test_create_bmc(self):
        """BMC can be created with required fields."""
        bmc = self.BMC.create({
            'name': 'Test Business Model',
        })
        self.assertEqual(bmc.state, 'draft')
        self.assertTrue(bmc.name)

    def test_bmc_lifecycle(self):
        """BMC follows draft → in_review → validated → archived lifecycle."""
        bmc = self.BMC.create({'name': 'Lifecycle Test'})
        self.assertEqual(bmc.state, 'draft')

        bmc.action_review()
        self.assertEqual(bmc.state, 'in_review')

        bmc.action_validate()
        self.assertEqual(bmc.state, 'validated')

        bmc.action_archive()
        self.assertEqual(bmc.state, 'archived')

        bmc.action_draft()
        self.assertEqual(bmc.state, 'draft')

    def test_bmc_blocks(self):
        """BMC 9 blocks can be populated."""
        bmc = self.BMC.create({
            'name': 'Block Test',
            'customer_segments': '<p>SME companies</p>',
            'value_propositions': '<p>Automated ERP</p>',
            'channels': '<p>Direct sales</p>',
            'customer_relationships': '<p>Personal assistance</p>',
            'revenue_streams': '<p>SaaS subscription</p>',
            'key_resources': '<p>Development team</p>',
            'key_activities': '<p>Product development</p>',
            'key_partnerships': '<p>Cloud providers</p>',
            'cost_structure': '<p>R&D 40%, Sales 30%</p>',
        })
        self.assertIn('SME', bmc.customer_segments)
        self.assertIn('Automated', bmc.value_propositions)

    def test_get_live_context(self):
        """get_live_context returns a dict with key metrics."""
        bmc = self.BMC.create({'name': 'Context Test'})
        ctx = bmc.get_live_context()
        self.assertIsInstance(ctx, dict)
        self.assertIn('customer_count', ctx)
        self.assertIn('product_count', ctx)

    def test_generated_by_tracking(self):
        """Generated by field records agent info."""
        bmc = self.BMC.create({
            'name': 'Agent Generated',
            'generated_by': 'pi-agent',
            'skill_version': '1.0.0',
        })
        self.assertEqual(bmc.generated_by, 'pi-agent')
        self.assertEqual(bmc.skill_version, '1.0.0')
