# Copyright (C) 2026 Vertel Sverige AB (<https://vertel.se>).
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).

from datetime import timedelta
import logging

from odoo import _, api, fields, models

_logger = logging.getLogger(__name__)


class BusinessModelCanvas(models.Model):
    """9-block Business Model Canvas — the core strategy artifact.
    Generated by Pi agents via XML-RPC or filled manually in Odoo UI.
    Data feeds into marketing.plan for execution."""

    _name = 'business.model.canvas'
    _description = 'Business Model Canvas'
    _inherit = ['mail.thread', 'mail.activity.mixin']
    _order = 'create_date desc, name'

    # -- Identity ----------------------------------------------------------
    name = fields.Char('Business Name', required=True)
    customer_id = fields.Many2one(
        'res.partner', 'Customer',
        domain=[('customer_rank', '>', 0)],
        help="The customer/company this BMC describes"
    )
    skill_id = fields.Many2one(
        'marketing.skill', 'Generated By Skill',
        help="Which skill generated this BMC (if AI-generated)"
    )

    # -- 9 BMC Blocks (Html for rich formatting) ---------------------------
    customer_segments = fields.Html('1. Customer Segments')
    value_propositions = fields.Html('2. Value Propositions')
    channels = fields.Html('3. Channels')
    customer_relationships = fields.Html('4. Customer Relationships')
    revenue_streams = fields.Html('5. Revenue Streams')
    key_resources = fields.Html('6. Key Resources')
    key_activities = fields.Html('7. Key Activities')
    key_partnerships = fields.Html('8. Key Partnerships')
    cost_structure = fields.Html('9. Cost Structure')

    # -- AI Generation metadata --------------------------------------------
    full_canvas_markdown = fields.Text('Full Canvas (Markdown)',
        help="Complete BMC as generated markdown")
    generated_by = fields.Char('Generated By', default='pi-agent')
    skill_version = fields.Char('Skill Version')

    # -- Status ------------------------------------------------------------
    state = fields.Selection([
        ('draft', 'Draft'),
        ('in_review', 'Under Review'),
        ('validated', 'Validated'),
        ('archived', 'Archived'),
    ], string='Status', default='draft', required=True, tracking=True)

    # -- Relationships -----------------------------------------------------
    plan_ids = fields.One2many(
        'marketing.plan', 'bmc_id',
        string='Marketing Plans',
        help="Marketing plans derived from this BMC"
    )
    swot_ids = fields.One2many(
        'swot.analysis', 'bmc_id',
        string='SWOT Analyses'
    )
    forecast_ids = fields.One2many(
        'strategy.forecast', 'bmc_id',
        string='Financial Forecasts'
    )

    # -- Metadata ----------------------------------------------------------
    company_id = fields.Many2one(
        'res.company', 'Company',
        default=lambda self: self.env.company
    )
    user_id = fields.Many2one(
        'res.users', 'Responsible',
        default=lambda self: self.env.user, tracking=True
    )

    # -- Actions -----------------------------------------------------------
    def action_validate(self):
        self.write({'state': 'validated'})

    def action_review(self):
        self.write({'state': 'in_review'})

    def action_draft(self):
        self.write({'state': 'draft'})

    def action_archive(self):
        self.write({'state': 'archived'})

    def get_live_context(self):
        """Return live Odoo data to underpin the BMC.
        Called by Pi agents before generating/iterating a BMC."""
        self.ensure_one()
        partner_domain = [('parent_id', '=', self.customer_id.id)] if self.customer_id else []
        if not partner_domain:
            partner_domain = [('customer_rank', '>', 0)]

        return {
            'customer_count': self.env['res.partner'].search_count(partner_domain),
            'lead_count': self.env['crm.lead'].search_count([
                ('partner_id', 'child_of', self.customer_id.id),
            ]) if self.customer_id else 0,
            'revenue_12m': sum(self.env['sale.order'].search([
                ('partner_id', 'child_of', self.customer_id.id),
                ('state', 'in', ['sale', 'done']),
                ('date_order', '>=', fields.Date.today() - timedelta(days=365)),
            ]).mapped('amount_total')) if self.customer_id else 0,
            'product_count': self.env['product.template'].search_count([]),
        }
