# Copyright (C) 2026 Vertel Sverige AB (<https://vertel.se>).
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).

from odoo import fields, models


class SWOTAnalysis(models.Model):
    _name = 'swot.analysis'
    _description = 'SWOT Analysis'
    _inherit = ['mail.thread', 'mail.activity.mixin']
    _order = 'create_date desc'

    name = fields.Char('Name', required=True)
    plan_id = fields.Many2one('strategy.plan', 'Strategic Plan', ondelete='set null')
    bmc_id = fields.Many2one('business.model.canvas', 'Business Model Canvas', ondelete='cascade')
    customer_id = fields.Many2one('res.partner', 'Customer')

    strengths = fields.Html('Strengths')
    weaknesses = fields.Html('Weaknesses')
    opportunities = fields.Html('Opportunities')
    threats = fields.Html('Threats')

    full_swot_markdown = fields.Text('Full SWOT (Markdown)')
    generated_by = fields.Char('Generated By', default='pi-agent')

    state = fields.Selection([
        ('draft', 'Draft'),
        ('validated', 'Validated'),
        ('archived', 'Archived'),
    ], default='draft', tracking=True)

    company_id = fields.Many2one('res.company', default=lambda self: self.env.company)
