# Copyright (C) 2026 Vertel Sverige AB (<https://vertel.se>).
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).

from odoo import fields, models


class ValuePropositionCanvas(models.Model):
    _name = 'value.proposition.canvas'
    _description = 'Value Proposition Canvas'
    _inherit = ['mail.thread']

    name = fields.Char('Name', required=True)
    bmc_id = fields.Many2one('business.model.canvas', 'Business Model Canvas', ondelete='cascade')
    plan_id = fields.Many2one('strategy.plan', 'Strategic Plan', ondelete='set null')
    customer_id = fields.Many2one('res.partner', 'Customer')

    # Customer Profile
    customer_jobs = fields.Html('Customer Jobs')
    pains = fields.Html('Pains')
    gains = fields.Html('Gains')

    # Value Map
    products_services = fields.Html('Products & Services')
    pain_relievers = fields.Html('Pain Relievers')
    gain_creators = fields.Html('Gain Creators')

    full_vpc_markdown = fields.Text('Full VPC (Markdown)')
    generated_by = fields.Char('Generated By', default='pi-agent')

    state = fields.Selection([
        ('draft', 'Draft'),
        ('validated', 'Validated'),
    ], default='draft')

    company_id = fields.Many2one('res.company', default=lambda self: self.env.company)
